name: Build Pipeline

on: [push, pull_request, workflow_dispatch]

jobs:
  Palladio-Analyzer-SimuLizar-Power:
    uses: PalladioSimulator/Palladio-Build-ActionsPipeline/.github/workflows/build.yml@master
    with:
      use-display-output: false
      no-caching: true
      deploy-updatesite: 'releng/org.palladiosimulator.simulizar.power.updatesite/target/repository'
    secrets:
      server-ssh-key: ${{ secrets.DEPLOYMENT_SERVER_SSH_KEY }}
      remote-host: ${{ secrets.DEPLOYMENT_REMOTE_HOST }}
      remote-port: ${{ secrets.DEPLOYMENT_REMOTE_PORT }}
      remote-user: ${{ secrets.DEPLOYMENT_REMOTE_USER }}
      remote-target: ${{ secrets.DEPLOYMENT_REMOTE_TARGET }}
